export const defaultData = [
  {
    id: "parent_1",
    name: "New Inquiry",
    total_price: 3200,
    total_leads: 2,
    children: [
      {
        id: 1,
        user_full_name: "John Doe",
        user_first_name: "John",
        amount: 100,
        close_date: "2023-11-15",
        assign_to: "Alice Smith",
      },
      {
        id: 2,
        user_full_name: "Jane Smith",
        user_first_name: "Jane",
        amount: 200,
        close_date: "2023-11-20",
        assign_to: "Bob Johnson",
      },
    ],
  },
  {
    id: "parent_2",
    name: "Hot Lead",
    total_price: 4500,
    total_leads: 3,
    children: [
      {
        id: 3,
        user_full_name: "Michael Brown",
        user_first_name: "Michael",
        amount: 300,
        close_date: "2023-11-25",
        assign_to: "Charlie Davis",
      },
      {
        id: 4,
        user_full_name: "Emily White",
        user_first_name: "Emily",
        amount: 400,
        close_date: "2023-11-30",
        assign_to: "Diana Evans",
      },
      {
        id: 5,
        user_full_name: "Chris Green",
        user_first_name: "Chris",
        amount: 500,
        close_date: "2023-12-05",
        assign_to: "Ethan Harris",
      },
    ],
  },
  {
    id: "parent_3",
    name: "Cold Lead",
    total_price: 2000,
    total_leads: 2,
    children: [
      {
        id: 6,
        user_full_name: "Sophia Wilson",
        user_first_name: "Sophia",
        amount: 150,
        close_date: "2023-12-10",
        assign_to: "Fiona Clark",
      },
      {
        id: 7,
        user_full_name: "Liam Martinez",
        user_first_name: "Liam",
        amount: 250,
        close_date: "2023-12-15",
        assign_to: "George Lewis",
      },
    ],
  },
  {
    id: "parent_4",
    name: "Proposal Sent",
    total_price: 3800,
    total_leads: 3,
    children: [
      {
        id: 8,
        user_full_name: "Olivia Hall",
        user_first_name: "Olivia",
        amount: 350,
        close_date: "2023-12-20",
        assign_to: "Hannah Walker",
      },
      {
        id: 9,
        user_full_name: "Noah Allen",
        user_first_name: "Noah",
        amount: 450,
        close_date: "2023-12-25",
        assign_to: "Isaac Young",
      },
      {
        id: 10,
        user_full_name: "Ava King",
        user_first_name: "Ava",
        amount: 550,
        close_date: "2023-12-30",
        assign_to: "Jack Wright",
      },
    ],
  },
  {
    id: "parent_5",
    name: "Negotiation",
    total_price: 5000,
    total_leads: 4,
    children: [
      {
        id: 11,
        user_full_name: "Mia Scott",
        user_first_name: "Mia",
        amount: 600,
        close_date: "2024-01-05",
        assign_to: "Karen Adams",
      },
      {
        id: 12,
        user_full_name: "Lucas Baker",
        user_first_name: "Lucas",
        amount: 700,
        close_date: "2024-01-10",
        assign_to: "Laura Nelson",
      },
      {
        id: 13,
        user_full_name: "Ella Perez",
        user_first_name: "Ella",
        amount: 800,
        close_date: "2024-01-15",
        assign_to: "Mark Carter",
      },
      {
        id: 14,
        user_full_name: "James Rivera",
        user_first_name: "James",
        amount: 900,
        close_date: "2024-01-20",
        assign_to: "Nina Mitchell",
      },
    ],
  },
  {
    id: "parent_6",
    name: "Won",
    total_price: 6000,
    total_leads: 5,
    children: [
      {
        id: 15,
        user_full_name: "Amelia Roberts",
        user_first_name: "Amelia",
        amount: 1000,
        close_date: "2024-01-25",
        assign_to: "Oscar Turner",
      },
      {
        id: 16,
        user_full_name: "Benjamin Phillips",
        user_first_name: "Benjamin",
        amount: 1100,
        close_date: "2024-01-30",
        assign_to: "Paula Campbell",
      },
      {
        id: 17,
        user_full_name: "Charlotte Parker",
        user_first_name: "Charlotte",
        amount: 1200,
        close_date: "2024-02-05",
        assign_to: "Quinn Edwards",
      },
      {
        id: 18,
        user_full_name: "Henry Morris",
        user_first_name: "Henry",
        amount: 1300,
        close_date: "2024-02-10",
        assign_to: "Rachel Hughes",
      },
      {
        id: 19,
        user_full_name: "Isabella Bell",
        user_first_name: "Isabella",
        amount: 1400,
        close_date: "2024-02-15",
        assign_to: "Samuel Foster",
      },
    ],
  },
  {
    id: "parent_7",
    name: "Lost",
    total_price: 7000,
    total_leads: 6,
    children: [
      {
        id: 20,
        user_full_name: "Ethan Ward",
        user_first_name: "Ethan",
        amount: 1500,
        close_date: "2024-02-20",
        assign_to: "Tina Gray",
      },
      {
        id: 21,
        user_full_name: "Harper Hughes",
        user_first_name: "Harper",
        amount: 1600,
        close_date: "2024-02-25",
        assign_to: "Uma Bennett",
      },
      {
        id: 22,
        user_full_name: "Alexander Ross",
        user_first_name: "Alexander",
        amount: 1700,
        close_date: "2024-03-01",
        assign_to: "Victor Simmons",
      },
      {
        id: 23,
        user_full_name: "Sophia Jenkins",
        user_first_name: "Sophia",
        amount: 1800,
        close_date: "2024-03-05",
        assign_to: "Wendy Peterson",
      },
      {
        id: 24,
        user_full_name: "Logan Kelly",
        user_first_name: "Logan",
        amount: 1900,
        close_date: "2024-03-10",
        assign_to: "Xavier Cooper",
      },
      {
        id: 25,
        user_full_name: "Grace Howard",
        user_first_name: "Grace",
        amount: 2000,
        close_date: "2024-03-15",
        assign_to: "Yvonne Bailey",
      },
    ],
  },
];
